import type { EsewaPaymentStatus } from "../../enums/eSewaPaymentStatus";

/**
 * EsewaPaymentRequest 
 * --------------------
 * Represents the request payload required to initiate a payment
 * transaction with the eSewa payment gateway
 * 
 * Note:
 *  - eSewa expects most values as strings.
 *  - Numbers are allowed here for developer convenience and should 
 *    be converted to strings before submitting the request.
 */
export interface EsewaPaymentRequest {
  /**
   * Base amount of the (product / service) excluding taxation. 
   */
  amount: string | number;
  
  /**
   * Taxation Amount applied to the (product / service) 
   */
  tax_amount: string | number;

  /**
   * Final Payable Amount.
   * Must be equal to: 
   * - amount + tax_amount + product_service_charge + product_delivery_charge
   */
  total_amount: string | number;

  /**
   * Unique Identifier for the transaction.
   * Should be generated per payment requests.
   */
  transaction_uuid: string;
  
  /**
   * Product or merchant code provided by eSewa.
   * Example: "EPAYTEST"
   * Note: 'EPAYTEST' is used for the sample eSewa payment integration. 
   */
  product_code: string;

  /**
   * Additional service charge (if any)
   * User "0" if not applicable
   */
  product_service_charge: string;

  /**
   * Delivery or shipping charge (if any)
   * Use "0" is not applicable
   */
  product_delivery_charge: string;

  /**
   * URL to which the user is redirected after a successful payment.
   * Callback function URL for success case.
   */
  success_url: string;  

  /**
   * URL to which the user is redirected if payment fails or is cancelled.
   * Callback function URL for failure case.
   */
  failure_url: string;

  /**
   * Comma-separated list of fields included in signature generation.
   * Example: "total_amount,transaction_uuid,product_code"
   */
  signed_field_names: string;

  /**
   * HMAC-SHA256 signature generated using the secret key
   * and the signed_field_names.
   */
  signature: string;
}


/**
 * EsewaPaymentResponse
 * --------------------
 * Represents the decoded response body returned by eSewa
 * after a payment transaction.
 *
 * IMPORTANT:
 * - The actual response is Base64 encoded.
 * - Decode it first, then parse the JSON.
 * - Always verify the signature to ensure data integrity.
 */
export interface EsewaPaymentSuccessResponse {
  /**
   * Unique transaction code generated by eSewa.
   */
  transaction_code: string;

  /**
   * Payment status.
   * Common values:
   * - COMPLETE
   * - FAILED
   * - PENDING
   */
  status: EsewaPaymentStatus;

  /**
   * Total amount paid by the customer.
   */
  total_amount: number | string;

  /**
   * Transaction UUID originally sent in the request.
   */
  transaction_uuid: string;

  /**
   * Merchant product code.
   */
  product_code: string;

  /**
   * Comma-separated list of fields used for signature generation.
   */
  signed_field_names: string;

  /**
   * HMAC-SHA256 signature generated by eSewa.
   * Used to verify response integrity.
   */
  signature: string;
}


export interface EsewaPaymentStatusCheck {
  /**
   * Transaction UUID originally sent in the request.
   */
  transaction_uuid: string;

  /**
   * Merchant product code.
   */
  product_code: string;

  /**
   * Total amount paid by the customer.
   */
  total_amount: number | string;
  
  /**
   * Payment status.
   */
  status: EsewaPaymentStatus;

  /**
   * eSewa reference ID
   * - Present for successful or refunded transactions
   * - null for pending or not found transactions
   */
  ref_id: string | null;
}


export interface EsewaServiceUnAvailable {
  code: number;
  /**
   * Error Message for the service unavailable.
   * Eg: Service is currently unavailable
   */
  error_message: string
}