export interface KhaltiCustomerInfo {
  name?: string;
  email?: string;
  phone?: string;
}

export interface KhaltiAmountBreakdown {
  label: string;
  amount: number;
}

export interface KhaltiProductDetails {
  identity: string;
  name: string;
  total_price: number;
  quantity: number;
  unit_price: number;
}


/**
 * KhaltiPaymentRequest
 * --------------------
 * Represents the request payload required to initiate a payment
 * transaction with the Khalti payment gateway.
 *
 * Note:
 *  - Khalti expects some values as numbers and some as strings.
 *  - Optional fields can be omitted.
 */
export interface KhaltiPaymentRequest {
  /** Required: Landing page after transaction */
  return_url: string;

  /** Required: Website URL / merchant domain */
  website_url: string;

  /** Required: Total payable amount in paisa (smallest currency unit) */
  amount: number;

  /** Required: Unique purchase order ID generated by merchant */
  purchase_order_id: string;

  /** Required: Name of the product / order */
  purchase_order_name: string;

  /** Optional: Customer info */
  customer_info?: KhaltiCustomerInfo;

  /** Optional: Amount breakdown array */
  amount_breakdown?: KhaltiAmountBreakdown[];

  /** Optional: Product details array */
  product_details?: KhaltiProductDetails[];

  /** Optional: Any merchant metadata starting with merchant_ */
  merchant_name?: string;
  merchant_extra?: string;
}

/**
 * KhaltiPaymentResponse
 * --------------------
 * Represents the response returned by Khalti after a payment transaction.
 */
export interface KhaltiPaymentResponse {
  /**
   * Unique transaction ID generated by Khalti.
   */
  transaction_id: string;

  /**
   * Payment amount.
   */
  amount: number;

  /**
   * Payment status.
   * Example: "Completed", "Failed", "Pending"
   */
  status: string;

  /**
   * Customer details.
   */
  customer_name?: string;
  customer_email?: string;
  mobile?: string;

  /**
   * Product details.
   */
  product_identity: string;
  product_name: string;
}


/**
 * Khalti Payload for KhaltiPaymentRequest
 */
// const payload: KhaltiPaymentRequest = {
//   return_url: "https://example.com/success",
//   website_url: "https://example.com",
//   amount: 1500, // in paisa (Rs 15.00)
//   purchase_order_id: "ORD123",
//   purchase_order_name: "Test Product",
//   customer_info: {
//     name: "Khalti User",
//     email: "user@example.com",
//     phone: "9800000001"
//   },
//   amount_breakdown: [
//     { label: "Product Price", amount: 1200 },
//     { label: "VAT", amount: 300 }
//   ],
//   product_details: [
//     {
//       identity: "PROD001",
//       name: "Test Product",
//       total_price: 1500,
//       quantity: 1,
//       unit_price: 1500
//     }
//   ],
//   merchant_name: "Example Merchant",
//   merchant_extra: "Extra info"
// };
